// utils/devicons.js
import {
    DiAndroid,
    DiApple,
    DiBootstrap,
    DiCode,
    DiCss3,
    DiDjango,
    DiDocker,
    DiFirebase,
    DiGit,
    DiGithubBadge,
    DiHtml5,
    DiJava,
    DiJavascript,
    DiLinux,
    DiMongodb,
    DiNodejs,
    DiPhp,
    DiPython,
    DiReact,
    DiRuby,
    DiRust,
    DiSass,
    DiVisualstudio,
    DiWordpress,
    DiYii,
} from "react-icons/di";

export const devicons = {
    android: DiAndroid,
    apple: DiApple,
    bootstrap: DiBootstrap,
    code: DiCode,
    css3: DiCss3,
    django: DiDjango,
    docker: DiDocker,
    firebase: DiFirebase,
    git: DiGit,
    github: DiGithubBadge,
    html5: DiHtml5,
    java: DiJava,
    javascript: DiJavascript,
    linux: DiLinux,
    mongodb: DiMongodb,
    nodejs: DiNodejs,
    php: DiPhp,
    python: DiPython,
    react: DiReact,
    ruby: DiRuby,
    rust: DiRust,
    sass: DiSass,
    visualstudio: DiVisualstudio,
    wordpress: DiWordpress,
    yii: DiYii,
};

// Helper function to retrieve an icon by key
export const getIcon = (key) => devicons[key] || null;
